import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='flex flex-col md:flex-row gap-3 justify-end px-10 py-5 border-b border-gray-800'>
          <Link href="/">Tareas</Link>
          <Link href="/new">Nueva tarea</Link>
        </nav>
        {children}
      </body>
    </html>
  )
}
